# Generated by Django 4.1.2 on 2022-11-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasabicalendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_by',
        ),
    ]
