# Generated by Django 4.1.1 on 2022-11-23 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wasabicalendar', '0002_remove_task_created_by_remove_task_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('slot', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='DictPair',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='tasks',
        ),
        migrations.AddField(
            model_name='tag',
            name='calendar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='wasabicalendar.calendar'),
        ),
        migrations.AddField(
            model_name='task',
            name='calendar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='wasabicalendar.calendar'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='updaters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='block',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='wasabicalendar.calendar'),
        ),
        migrations.AddField(
            model_name='block',
            name='select_user',
            field=models.ManyToManyField(related_name='toblocks', to=settings.AUTH_USER_MODEL),
        ),
    ]
