# Generated by Django 4.1.2 on 2022-11-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wasabicalendar', '0003_block_delete_dictpair_remove_calendar_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tsk', to='wasabicalendar.tag'),
        ),
    ]
