# Generated by Django 4.1.1 on 2022-11-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasabicalendar', '0004_alter_task_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#FF0000', max_length=7),
        ),
    ]
