# Generated by Django 4.1.1 on 2022-11-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasabicalendar', '0005_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#4B5B1B', max_length=7),
        ),
    ]
