# Generated by Django 4.1.1 on 2022-11-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasabicalendar', '0006_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
