# Generated by Django 4.1.2 on 2022-11-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasabicalendar', '0007_alter_calendar_name_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#E3F1BA', max_length=7),
        ),
    ]
